#!/bin/bash
tmp=$(mktemp -d)
cd $tmp
touch -d '1918-11-11 11:00 GMT' wwi-armistice-cs35L
touch now
sleep 1
touch now1
TZ=UTC0 ls -lt --full-time wwi-armistice-cs35L now now1
echo ""
testls=$HOME/Documents/CS35L/Assignment4/Lab/coreutils-with-bug/src/ls
TZ=UTC0 $testls -lt --full-time wwi-armistice-cs35L now now1
cd
rm -fr $tmp
